<?php


namespace App\Models;

use Eloquent as Model;
use Illuminate\Support\Facades\Schema;

abstract class BaseModel extends Model
{

    const ABSOLUTE = 'absolute';
    const RELATIVE = 'relative';

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);
    }

    public function replicate(array $except = null) {

        $replicate = parent::replicate();
        $replicate->save();
        $replicate->syntheticIdQuestionWithLevel();
        return $replicate;
    }

    public function newQuery(): \Illuminate\Database\Eloquent\Builder
    {
        if (\Auth::user()?->isAdmin()) {
            return parent::newQuery();
        }
        $product_id = !empty(\Auth::user()->product_id) ? \Auth::user()->product_id : null;
        if (isset($this->isFilterProduct) && $this->isFilterProduct && $product_id) {
            $this->addGlobalScope('product_id', function (\Illuminate\Database\Eloquent\Builder $builder) use ($product_id) {
                $builder->where('product_id', '=', $product_id)->orWhere('product_id','=',null);
            });

        }

        return parent::newQuery(); // TODO: Change the autogenerated stub
    }

    public function syntheticIdQuestionWithLevel($destroy = false) {
        return $this;
    }
}
